export const kanbanMockData = [
    {
      id: 'task-1',
      title: 'Research competitors',
      description: 'Gather data on top 5 competitors for the report.',
      assignee: 'Alice',
      stage: 'backlog',
      priority: 'medium',
    },
    {
      id: 'task-2',
      title: 'Design homepage wireframe',
      description: 'Create Figma wireframes for the new homepage layout.',
      assignee: 'Bob',
      stage: 'todo',
      priority: 'high',
    },
    {
      id: 'task-3',
      title: 'Setup CI/CD pipeline',
      description: 'Configure GitHub Actions for automatic deployment.',
      assignee: 'Charlie',
      stage: 'inprogress',
      priority: 'high',
    },
    {
      id: 'task-4',
      title: 'Write user authentication logic',
      description: 'Implement login and registration using JWT.',
      assignee: 'Diana',
      stage: 'inprogress',
      priority: 'high',
    },
    {
      id: 'task-5',
      title: 'Fix broken links',
      description: 'Audit and fix all 404 links in the application.',
      assignee: 'Evan',
      stage: 'todo',
      priority: 'low',
    },
    {
      id: 'task-6',
      title: 'Deploy to production',
      description: 'Deploy version 1.0 to the production server.',
      assignee: 'Fiona',
      stage: 'done',
      priority: 'critical',
    },
    {
      id: 'task-7',
      title: 'User feedback review',
      description: 'Analyze user feedback from the last release.',
      assignee: 'George',
      stage: 'done',
      priority: 'medium',
    },
  ];
  